# Generated by Django 3.2.13 on 2022-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20220714_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='dfrrr', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
